apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- study-tracker-api
- study-tracker-web
namespace: study-tracker
namePrefix: prod-
images:
- name: ghcr.io/ramoncollazo/study-tracker-api
  newName: ghcr.io/ramoncollazo/study-tracker-api
  newTag: v0.3.2
- name: ghcr.io/ramoncollazo/study-tracker-web
  newTag: v0.2.1
