apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - study-tracker-api
  - study-tracker-web
namespace: study-tracker
namePrefix: dev-
images:
  - name: study-tracker-api
    newTag: dev
  - name: study-tracker-web
    newTag: dev
