apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/study-tracker-web/
# Patch for the frontend deployment
patches:
  - target:
      kind: Deployment
      name: study-tracker-web
      namespace: study-tracker
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env
        value:
          - name: DEBUG
            value: "true"
          - name: API_URL
            value: "http://dev-study-tracker-api:3001"
